In [ ]:
!git clone https://github.com/taehojo/data.git

Cloning into 'data'...
remote: Enumerating objects: 36, done.
remote: Counting objects: 100% (36/36), done.
remote: Compressing objects: 100% (29/29), done.
remote: Total 36 (delta 9), reused 26 (delta 4), pack-reused 0 (from 0)
Receiving objects: 100% (36/36), 483.12 KiB | 10.06 MiB/s, done.
Resolving deltas: 100% (9/9), done.

In [ ]:
import pandas as pd

df = pd.read_csv('/content/data/house_train.csv')
df

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,RL,62.0,7917,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,175000
1456,1457,20,RL,85.0,13175,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,2,2010,WD,Normal,210000
1457,1458,70,RL,66.0,9042,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,GdPrv,Shed,2500,5,2010,WD,Normal,266500
1458,1459,20,RL,68.0,9717,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,142125
1459,1460,20,RL,75.0,9937,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2008,WD,Normal,147500

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 81 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1460 non-null   int64
 1   MSSubClass     1460 non-null   int64
 2   MSZoning       1460 non-null   object
 3   LotFrontage    1201 non-null   float64
 4   LotArea        1460 non-null   int64
 5   Street         1460 non-null   object
 6   Alley          91 non-null     object
 7   LotShape       1460 non-null   object
 8   LandContour    1460 non-null   object
 9   Utilities      1460 non-null   object
 10  LotConfig      1460 non-null   object
 11  LandSlope      1460 non-null   object
 12  Neighborhood   1460 non-null   object
 13  Condition1     1460 non-null   object
 14  Condition2     1460 non-null   object
 15  BldgType       1460 non-null   object
 16  HouseStyle     1460 non-null   object
 17  OverallQual    1460 non-null   int64
 18  OverallCond    1460 non-null   int64
 19  YearBuilt      1460 non-null   int64
 20  YearRemodAdd   1460 non-null   int64
 21  RoofStyle      1460 non-null   object
 22  RoofMatl       1460 non-null   object
 23  Exterior1st    1460 non-null   object
 24  Exterior2nd    1460 non-null   object
 25  MasVnrType     588 non-null    object
 26  MasVnrArea     1452 non-null   float64
 27  ExterQual      1460 non-null   object
 28  ExterCond      1460 non-null   object
 29  Foundation     1460 non-null   object
 30  BsmtQual       1423 non-null   object
 31  BsmtCond       1423 non-null   object
 32  BsmtExposure   1422 non-null   object
 33  BsmtFinType1   1423 non-null   object
 34  BsmtFinSF1     1460 non-null   int64
 35  BsmtFinType2   1422 non-null   object
 36  BsmtFinSF2     1460 non-null   int64
 37  BsmtUnfSF      1460 non-null   int64
 38  TotalBsmtSF    1460 non-null   int64
 39  Heating        1460 non-null   object
 40  HeatingQC      1460 non-null   object
 41  CentralAir     1460 non-null   object
 42  Electrical     1459 non-null   object
 43  1stFlrSF       1460 non-null   int64
 44  2ndFlrSF       1460 non-null   int64
 45  LowQualFinSF   1460 non-null   int64
 46  GrLivArea      1460 non-null   int64
 47  BsmtFullBath   1460 non-null   int64
 48  BsmtHalfBath   1460 non-null   int64
 49  FullBath       1460 non-null   int64
 50  HalfBath       1460 non-null   int64
 51  BedroomAbvGr   1460 non-null   int64
 52  KitchenAbvGr   1460 non-null   int64
 53  KitchenQual    1460 non-null   object
 54  TotRmsAbvGrd   1460 non-null   int64
 55  Functional     1460 non-null   object
 56  Fireplaces     1460 non-null   int64
 57  FireplaceQu    770 non-null    object
 58  GarageType     1379 non-null   object
 59  GarageYrBlt    1379 non-null   float64
 60  GarageFinish   1379 non-null   object
 61  GarageCars     1460 non-null   int64
 62  GarageArea     1460 non-null   int64
 63  GarageQual     1379 non-null   object
 64  GarageCond     1379 non-null   object
 65  PavedDrive     1460 non-null   object
 66  WoodDeckSF     1460 non-null   int64
 67  OpenPorchSF    1460 non-null   int64
 68  EnclosedPorch  1460 non-null   int64
 69  3SsnPorch      1460 non-null   int64
 70  ScreenPorch    1460 non-null   int64
 71  PoolArea       1460 non-null   int64
 72  PoolQC         7 non-null      object
 73  Fence          281 non-null    object
 74  MiscFeature    54 non-null     object
 75  MiscVal        1460 non-null   int64
 76  MoSold         1460 non-null   int64
 77  YrSold         1460 non-null   int64
 78  SaleType       1460 non-null   object
 79  SaleCondition  1460 non-null   object
 80  SalePrice      1460 non-null   int64
dtypes: float64(3), int64(35), object(43)
memory usage: 924.0+ KB

In [ ]:
df_encoded = pd.get_dummies(df)
display(df_encoded.head())

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,SaleType_ConLw,SaleType_New,SaleType_Oth,SaleType_WD,SaleCondition_Abnorml,SaleCondition_AdjLand,SaleCondition_Alloca,SaleCondition_Family,SaleCondition_Normal,SaleCondition_Partial
0,1,60,65.0,8450,7,5,2003,2003,196.0,706,...,False,False,False,True,False,False,False,False,True,False
1,2,20,80.0,9600,6,8,1976,1976,0.0,978,...,False,False,False,True,False,False,False,False,True,False
2,3,60,68.0,11250,7,5,2001,2002,162.0,486,...,False,False,False,True,False,False,False,False,True,False
3,4,70,60.0,9550,7,5,1915,1970,0.0,216,...,False,False,False,True,True,False,False,False,False,False
4,5,60,84.0,14260,8,5,2000,2000,350.0,655,...,False,False,False,True,False,False,False,False,True,False

In [ ]:
df_encoded.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Columns: 289 entries, Id to SaleCondition_Partial
dtypes: bool(251), float64(3), int64(35)
memory usage: 791.4 KB

In [ ]:
df_encoded.head(100)

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,SaleType_ConLw,SaleType_New,SaleType_Oth,SaleType_WD,SaleCondition_Abnorml,SaleCondition_AdjLand,SaleCondition_Alloca,SaleCondition_Family,SaleCondition_Normal,SaleCondition_Partial
0,1,60,65.0,8450,7,5,2003,2003,196.0,706,...,False,False,False,True,False,False,False,False,True,False
1,2,20,80.0,9600,6,8,1976,1976,0.0,978,...,False,False,False,True,False,False,False,False,True,False
2,3,60,68.0,11250,7,5,2001,2002,162.0,486,...,False,False,False,True,False,False,False,False,True,False
3,4,70,60.0,9550,7,5,1915,1970,0.0,216,...,False,False,False,True,True,False,False,False,False,False
4,5,60,84.0,14260,8,5,2000,2000,350.0,655,...,False,False,False,True,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,60,NaN,9765,6,8,1993,1993,68.0,310,...,False,False,False,True,False,False,False,False,True,False
96,97,20,78.0,10264,7,5,1999,1999,183.0,1162,...,False,False,False,True,False,False,False,False,True,False
97,98,20,73.0,10921,4,5,1965,1965,48.0,520,...,False,False,False,True,False,False,False,False,True,False
98,99,30,85.0,10625,5,5,1920,1950,0.0,108,...,False,False,False,False,True,False,False,False,False,False
99,100,20,77.0,9320,4,5,1959,1959,0.0,569,...,False,False,False,True,False,False,False,False,True,False

In [ ]:
df_encoded.isnull().sum().sort_values(ascending=False)

LotFrontage          259
GarageYrBlt           81
MasVnrArea             8
BsmtFinType1_GLQ       0
BsmtFinType1_ALQ       0
                    ...
Condition1_PosN        0
Condition1_PosA        0
Condition1_Norm        0
Condition1_Feedr       0
Condition2_Artery      0
Length: 289, dtype: int64

In [ ]:
# df_encoded = df_encoded.dropna(df_encoded.mean())
df_encoded = df_encoded.fillna(df_encoded.mean())

In [ ]:
df_encoded.isnull().sum().sort_values(ascending=False)

SaleCondition_Partial    0
GarageFinish_Unf         0
GarageQual_Ex            0
GarageQual_Fa            0
GarageQual_Gd            0
                        ..
OverallQual              0
OverallCond              0
YearBuilt                0
YearRemodAdd             0
MasVnrArea               0
Length: 289, dtype: int64

In [ ]:
X = df_encoded.drop('SalePrice', axis=1)
y = df_encoded['SalePrice']

X, y

(        Id  MSSubClass  LotFrontage  LotArea  OverallQual  OverallCond  \
 0        1          60         65.0     8450            7            5
 1        2          20         80.0     9600            6            8
 2        3          60         68.0    11250            7            5
 3        4          70         60.0     9550            7            5
 4        5          60         84.0    14260            8            5
 ...    ...         ...          ...      ...          ...          ...
 1455  1456          60         62.0     7917            6            5
 1456  1457          20         85.0    13175            6            6
 1457  1458          70         66.0     9042            7            9
 1458  1459          20         68.0     9717            5            6
 1459  1460          20         75.0     9937            5            6

       YearBuilt  YearRemodAdd  MasVnrArea  BsmtFinSF1  ...  SaleType_ConLw  \
 0          2003          2003       196.0         706  ...           False
 1          1976          1976         0.0         978  ...           False
 2          2001          2002       162.0         486  ...           False
 3          1915          1970         0.0         216  ...           False
 4          2000          2000       350.0         655  ...           False
 ...         ...           ...         ...         ...  ...             ...
 1455       1999          2000         0.0           0  ...           False
 1456       1978          1988       119.0         790  ...           False
 1457       1941          2006         0.0         275  ...           False
 1458       1950          1996         0.0          49  ...           False
 1459       1965          1965         0.0         830  ...           False

       SaleType_New  SaleType_Oth  SaleType_WD  SaleCondition_Abnorml  \
 0            False         False         True                  False
 1            False         False         True                  False
 2            False         False         True                  False
 3            False         False         True                   True
 4            False         False         True                  False
 ...            ...           ...          ...                    ...
 1455         False         False         True                  False
 1456         False         False         True                  False
 1457         False         False         True                  False
 1458         False         False         True                  False
 1459         False         False         True                  False

       SaleCondition_AdjLand  SaleCondition_Alloca  SaleCondition_Family  \
 0                     False                 False                 False
 1                     False                 False                 False
 2                     False                 False                 False
 3                     False                 False                 False
 4                     False                 False                 False
 ...                     ...                   ...                   ...
 1455                  False                 False                 False
 1456                  False                 False                 False
 1457                  False                 False                 False
 1458                  False                 False                 False
 1459                  False                 False                 False

       SaleCondition_Normal  SaleCondition_Partial
 0                     True                  False
 1                     True                  False
 2                     True                  False
 3                    False                  False
 4                     True                  False
 ...                    ...                    ...
 1455                  True                  False
 1456                  True                  False
 1457                  True                  False
 1458                  True                  False
 1459                  True                  False

 [1460 rows x 288 columns],
 0       208500
 1       181500
 2       223500
 3       140000
 4       250000
          ...
 1455    175000
 1456    210000
 1457    266500
 1458    142125
 1459    147500
 Name: SalePrice, Length: 1460, dtype: int64)

In [ ]:
import tensorflow as tf
from tensorflow import keras
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import numpy as np

In [ ]:
# ### 훈련 및 테스트 데이터 분할
# 모델 훈련을 위해 데이터를 훈련 세트와 테스트 세트로 분할합니다. 또한, 스케일링을 통해 데이터의 범위를 조정하여 모델 훈련의 안정성을 높입니다.
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

print(f"훈련 세트 크기: {X_train_scaled.shape}")
print(f"테스트 세트 크기: {X_test_scaled.shape}")

훈련 세트 크기: (1168, 288)
테스트 세트 크기: (292, 288)

In [ ]:
# ### 딥러닝 모델 구성
# 간단한 신경망 모델을 구성합니다. 입력층, 여러 개의 은닉층(Dense layer), 그리고 출력층으로 이루어져 있습니다. 출력층은 회귀 문제이므로 활성화 함수가 없습니다.
model = keras.Sequential([
    keras.layers.Dense(128, activation='relu', input_shape=(X_train_scaled.shape[1],)),
    keras.layers.Dropout(0.2),
    keras.layers.Dense(64, activation='relu'),
    keras.layers.Dropout(0.2),
    keras.layers.Dense(32, activation='relu'),
    keras.layers.Dense(1) # 회귀 문제이므로 출력층은 1개의 뉴런을 가지며 활성화 함수 없음
])

model.summary()

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_4 (Dense)                 │ (None, 128)            │        17,024 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_2 (Dropout)             │ (None, 128)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 64)             │         8,256 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_3 (Dropout)             │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_6 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_7 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 27,393 (107.00 KB)

 Trainable params: 27,393 (107.00 KB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
# ### 모델 컴파일
# 모델을 훈련하기 전에 컴파일 단계를 거쳐야 합니다. 옵티마이저(optimizer), 손실 함수(loss function), 그리고 평가 지표(metrics)를 정의합니다. 회귀 문제이므로 손실 함수는 'mse'(평균 제곱 오차)를 사용합니다.
model.compile(optimizer='adam', loss='mse', metrics=['mae', 'mse'])

In [ ]:
from tensorflow import keras

# ### Early Stopping (조기 종료) 설정
# 모델이 과적합되는 것을 방지하고 훈련 시간을 단축하기 위해 조기 종료 콜백을 설정합니다.
# `patience`는 검증 손실이 개선되지 않아도 훈련을 중지하기 전까지 기다릴 에포크 수를 의미합니다.
early_stopping = keras.callbacks.EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)

In [ ]:
# ### 모델 훈련
# 정의된 모델을 훈련 데이터로 학습시킵니다. `epochs`는 전체 훈련 세트를 몇 번 반복하여 학습할지, `batch_size`는 한 번에 처리할 샘플의 크기를 의미합니다.
history = model.fit(X_train_scaled, y_train, epochs=100, batch_size=32, validation_split=0.2, verbose=1, callbacks=[early_stopping])

Epoch 1/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 5s 72ms/step - loss: 39144472576.0000 - mae: 181520.0781 - mse: 39144472576.0000 - val_loss: 37834469376.0000 - val_mae: 181082.8594 - val_mse: 37834469376.0000
Epoch 2/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 39119835136.0000 - mae: 181463.0469 - mse: 39119835136.0000 - val_loss: 37775863808.0000 - val_mae: 180947.9688 - val_mse: 37775863808.0000
Epoch 3/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 38967480320.0000 - mae: 181124.3750 - mse: 38967480320.0000 - val_loss: 37465493504.0000 - val_mae: 180255.5312 - val_mse: 37465493504.0000
Epoch 4/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 38306590720.0000 - mae: 179696.3438 - mse: 38306590720.0000 - val_loss: 36376649728.0000 - val_mae: 177822.8594 - val_mse: 36376649728.0000
Epoch 5/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 36353748992.0000 - mae: 175456.4219 - mse: 36353748992.0000 - val_loss: 33650694144.0000 - val_mae: 171528.1406 - val_mse: 33650694144.0000
Epoch 6/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 32496343040.0000 - mae: 166374.7500 - mse: 32496343040.0000 - val_loss: 28774565888.0000 - val_mae: 159362.0781 - val_mse: 28774565888.0000
Epoch 7/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 26351196160.0000 - mae: 150221.3906 - mse: 26351196160.0000 - val_loss: 21608308736.0000 - val_mae: 138582.3438 - val_mse: 21608308736.0000
Epoch 8/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 18286041088.0000 - mae: 124208.6328 - mse: 18286041088.0000 - val_loss: 13683483648.0000 - val_mae: 108236.2109 - val_mse: 13683483648.0000
Epoch 9/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 11245672448.0000 - mae: 92384.6875 - mse: 11245672448.0000 - val_loss: 8325313024.0000 - val_mae: 77814.6719 - val_mse: 8325313024.0000
Epoch 10/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7403916800.0000 - mae: 69954.5000 - mse: 7403916800.0000 - val_loss: 6097853440.0000 - val_mae: 63419.5625 - val_mse: 6097853440.0000
Epoch 11/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6039985152.0000 - mae: 60946.8047 - mse: 6039985152.0000 - val_loss: 5031408640.0000 - val_mae: 56837.0742 - val_mse: 5031408640.0000
Epoch 12/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 5210601984.0000 - mae: 55370.6914 - mse: 5210601984.0000 - val_loss: 4336242688.0000 - val_mae: 51779.7578 - val_mse: 4336242688.0000
Epoch 13/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 4429477888.0000 - mae: 50267.1719 - mse: 4429477888.0000 - val_loss: 3802414592.0000 - val_mae: 47833.7422 - val_mse: 3802414592.0000
Epoch 14/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 3943431936.0000 - mae: 46792.3516 - mse: 3943431936.0000 - val_loss: 3413418752.0000 - val_mae: 44527.5000 - val_mse: 3413418752.0000
Epoch 15/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 3771864832.0000 - mae: 44335.3789 - mse: 3771864832.0000 - val_loss: 3153469696.0000 - val_mae: 42191.4531 - val_mse: 3153469696.0000
Epoch 16/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 3384359936.0000 - mae: 42987.7656 - mse: 3384359936.0000 - val_loss: 2945861632.0000 - val_mae: 40345.6211 - val_mse: 2945861632.0000
Epoch 17/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 3381779200.0000 - mae: 40329.8086 - mse: 3381779200.0000 - val_loss: 2804270336.0000 - val_mae: 39063.8320 - val_mse: 2804270336.0000
Epoch 18/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 3187441920.0000 - mae: 40437.0234 - mse: 3187441920.0000 - val_loss: 2696111616.0000 - val_mae: 38072.2734 - val_mse: 2696111616.0000
Epoch 19/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 2900576256.0000 - mae: 39203.2695 - mse: 2900576256.0000 - val_loss: 2599508736.0000 - val_mae: 37231.0898 - val_mse: 2599508736.0000
Epoch 20/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 2778776064.0000 - mae: 36959.5000 - mse: 2778776064.0000 - val_loss: 2503263488.0000 - val_mae: 36443.4922 - val_mse: 2503263488.0000
Epoch 21/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 2716784896.0000 - mae: 37462.4180 - mse: 2716784896.0000 - val_loss: 2437969152.0000 - val_mae: 35921.7188 - val_mse: 2437969152.0000
Epoch 22/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 2661507584.0000 - mae: 36577.3516 - mse: 2661507584.0000 - val_loss: 2370028288.0000 - val_mae: 35347.4023 - val_mse: 2370028288.0000
Epoch 23/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 2642170368.0000 - mae: 36779.4805 - mse: 2642170368.0000 - val_loss: 2303446272.0000 - val_mae: 34779.4492 - val_mse: 2303446272.0000
Epoch 24/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 2512533760.0000 - mae: 36061.3789 - mse: 2512533760.0000 - val_loss: 2249046784.0000 - val_mae: 34332.3086 - val_mse: 2249046784.0000
Epoch 25/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 2615633920.0000 - mae: 35371.6719 - mse: 2615633920.0000 - val_loss: 2209741312.0000 - val_mae: 33845.8086 - val_mse: 2209741312.0000
Epoch 26/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 2484315648.0000 - mae: 35282.4727 - mse: 2484315648.0000 - val_loss: 2148398592.0000 - val_mae: 33479.9961 - val_mse: 2148398592.0000
Epoch 27/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 2279701248.0000 - mae: 33980.6055 - mse: 2279701248.0000 - val_loss: 2107644544.0000 - val_mae: 33257.4648 - val_mse: 2107644544.0000
Epoch 28/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 2181807104.0000 - mae: 33202.2422 - mse: 2181807104.0000 - val_loss: 2055441792.0000 - val_mae: 32892.3867 - val_mse: 2055441792.0000
Epoch 29/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 2292283392.0000 - mae: 33197.5195 - mse: 2292283392.0000 - val_loss: 2009570048.0000 - val_mae: 32589.4785 - val_mse: 2009570048.0000
Epoch 30/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 2197392128.0000 - mae: 33581.0625 - mse: 2197392128.0000 - val_loss: 1977798912.0000 - val_mae: 32205.6738 - val_mse: 1977798912.0000
Epoch 31/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 2109294080.0000 - mae: 32698.5176 - mse: 2109294080.0000 - val_loss: 1931727872.0000 - val_mae: 31935.7031 - val_mse: 1931727872.0000
Epoch 32/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 2178363648.0000 - mae: 32675.0488 - mse: 2178363648.0000 - val_loss: 1898642304.0000 - val_mae: 31621.7852 - val_mse: 1898642304.0000
Epoch 33/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1982112896.0000 - mae: 31336.0762 - mse: 1982112896.0000 - val_loss: 1854649728.0000 - val_mae: 31257.5176 - val_mse: 1854649728.0000
Epoch 34/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 2000348544.0000 - mae: 32390.2734 - mse: 2000348544.0000 - val_loss: 1815799680.0000 - val_mae: 30964.8809 - val_mse: 1815799680.0000
Epoch 35/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1912582528.0000 - mae: 31472.4824 - mse: 1912582528.0000 - val_loss: 1778974720.0000 - val_mae: 30705.5742 - val_mse: 1778974720.0000
Epoch 36/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1933645696.0000 - mae: 30520.4512 - mse: 1933645696.0000 - val_loss: 1753710080.0000 - val_mae: 30550.6152 - val_mse: 1753710080.0000
Epoch 37/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1899231872.0000 - mae: 30277.1348 - mse: 1899231872.0000 - val_loss: 1725821440.0000 - val_mae: 30506.7285 - val_mse: 1725821440.0000
Epoch 38/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1844260736.0000 - mae: 30953.6875 - mse: 1844260736.0000 - val_loss: 1701196672.0000 - val_mae: 30172.6094 - val_mse: 1701196672.0000
Epoch 39/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1887324416.0000 - mae: 31026.5879 - mse: 1887324416.0000 - val_loss: 1673595904.0000 - val_mae: 29877.5371 - val_mse: 1673595904.0000
Epoch 40/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1789296512.0000 - mae: 29754.2402 - mse: 1789296512.0000 - val_loss: 1638733440.0000 - val_mae: 29589.4238 - val_mse: 1638733440.0000
Epoch 41/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1702862720.0000 - mae: 29514.7422 - mse: 1702862720.0000 - val_loss: 1602967424.0000 - val_mae: 29366.5938 - val_mse: 1602967424.0000
Epoch 42/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1657223552.0000 - mae: 28806.3809 - mse: 1657223552.0000 - val_loss: 1586289920.0000 - val_mae: 29232.8320 - val_mse: 1586289920.0000
Epoch 43/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1735574912.0000 - mae: 29446.3691 - mse: 1735574912.0000 - val_loss: 1563546368.0000 - val_mae: 29020.6973 - val_mse: 1563546368.0000
Epoch 44/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1686792192.0000 - mae: 28927.9980 - mse: 1686792192.0000 - val_loss: 1547368576.0000 - val_mae: 28930.9297 - val_mse: 1547368576.0000
Epoch 45/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1706684544.0000 - mae: 29273.8457 - mse: 1706684544.0000 - val_loss: 1521712000.0000 - val_mae: 28597.2285 - val_mse: 1521712000.0000
Epoch 46/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1568714240.0000 - mae: 28395.5996 - mse: 1568714240.0000 - val_loss: 1502529792.0000 - val_mae: 28470.3613 - val_mse: 1502529792.0000
Epoch 47/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1579567488.0000 - mae: 28616.1348 - mse: 1579567488.0000 - val_loss: 1482977280.0000 - val_mae: 28294.9238 - val_mse: 1482977280.0000
Epoch 48/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1512105856.0000 - mae: 28510.2871 - mse: 1512105856.0000 - val_loss: 1466659456.0000 - val_mae: 28063.3242 - val_mse: 1466659456.0000
Epoch 49/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1630035840.0000 - mae: 28244.6660 - mse: 1630035840.0000 - val_loss: 1436575744.0000 - val_mae: 27916.5234 - val_mse: 1436575744.0000
Epoch 50/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1445952256.0000 - mae: 27550.7402 - mse: 1445952256.0000 - val_loss: 1432101248.0000 - val_mae: 27648.1680 - val_mse: 1432101248.0000
Epoch 51/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1453672320.0000 - mae: 27223.7383 - mse: 1453672320.0000 - val_loss: 1409076608.0000 - val_mae: 27490.9219 - val_mse: 1409076608.0000
Epoch 52/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1579684352.0000 - mae: 28510.0527 - mse: 1579684352.0000 - val_loss: 1381783296.0000 - val_mae: 27363.9004 - val_mse: 1381783296.0000
Epoch 53/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1505280640.0000 - mae: 27925.8652 - mse: 1505280640.0000 - val_loss: 1382489344.0000 - val_mae: 27229.2891 - val_mse: 1382489344.0000
Epoch 54/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1447269632.0000 - mae: 27723.4473 - mse: 1447269632.0000 - val_loss: 1360274688.0000 - val_mae: 27086.7773 - val_mse: 1360274688.0000
Epoch 55/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1360480640.0000 - mae: 26197.5273 - mse: 1360480640.0000 - val_loss: 1343501568.0000 - val_mae: 27028.1348 - val_mse: 1343501568.0000
Epoch 56/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1365872128.0000 - mae: 26103.2637 - mse: 1365872128.0000 - val_loss: 1350921344.0000 - val_mae: 27090.4180 - val_mse: 1350921344.0000
Epoch 57/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1503204096.0000 - mae: 27944.2031 - mse: 1503204096.0000 - val_loss: 1337478400.0000 - val_mae: 26806.9062 - val_mse: 1337478400.0000
Epoch 58/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1348799232.0000 - mae: 26911.6641 - mse: 1348799232.0000 - val_loss: 1322411136.0000 - val_mae: 26623.8496 - val_mse: 1322411136.0000
Epoch 59/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1307024896.0000 - mae: 26368.8145 - mse: 1307024896.0000 - val_loss: 1317009792.0000 - val_mae: 26548.5000 - val_mse: 1317009792.0000
Epoch 60/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1261543680.0000 - mae: 26033.5410 - mse: 1261543680.0000 - val_loss: 1309471360.0000 - val_mae: 26487.7676 - val_mse: 1309471360.0000
Epoch 61/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1260544640.0000 - mae: 25864.5840 - mse: 1260544640.0000 - val_loss: 1298234880.0000 - val_mae: 26274.5820 - val_mse: 1298234880.0000
Epoch 62/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1273403520.0000 - mae: 25742.4219 - mse: 1273403520.0000 - val_loss: 1287014016.0000 - val_mae: 26327.5352 - val_mse: 1287014016.0000
Epoch 63/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1296539008.0000 - mae: 26335.6406 - mse: 1296539008.0000 - val_loss: 1269329408.0000 - val_mae: 26080.0508 - val_mse: 1269329408.0000
Epoch 64/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1299073792.0000 - mae: 26262.6191 - mse: 1299073792.0000 - val_loss: 1264495616.0000 - val_mae: 26029.6426 - val_mse: 1264495616.0000
Epoch 65/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1202029568.0000 - mae: 25090.0762 - mse: 1202029568.0000 - val_loss: 1264727296.0000 - val_mae: 26073.6426 - val_mse: 1264727296.0000
Epoch 66/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1283468544.0000 - mae: 25752.9590 - mse: 1283468544.0000 - val_loss: 1255550336.0000 - val_mae: 25766.3496 - val_mse: 1255550336.0000
Epoch 67/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1216409344.0000 - mae: 24838.7148 - mse: 1216409344.0000 - val_loss: 1238214784.0000 - val_mae: 25572.9355 - val_mse: 1238214784.0000
Epoch 68/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1199260672.0000 - mae: 25267.0898 - mse: 1199260672.0000 - val_loss: 1224708736.0000 - val_mae: 25626.8262 - val_mse: 1224708736.0000
Epoch 69/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 1082304768.0000 - mae: 24567.0312 - mse: 1082304768.0000 - val_loss: 1210757632.0000 - val_mae: 25363.2637 - val_mse: 1210757632.0000
Epoch 70/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1153980544.0000 - mae: 25138.1914 - mse: 1153980544.0000 - val_loss: 1208227712.0000 - val_mae: 25191.2441 - val_mse: 1208227712.0000
Epoch 71/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1186567808.0000 - mae: 24907.9102 - mse: 1186567808.0000 - val_loss: 1189607040.0000 - val_mae: 25119.6797 - val_mse: 1189607040.0000
Epoch 72/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 1160641280.0000 - mae: 24218.7832 - mse: 1160641280.0000 - val_loss: 1186599680.0000 - val_mae: 25085.5586 - val_mse: 1186599680.0000
Epoch 73/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 1197682688.0000 - mae: 24789.3379 - mse: 1197682688.0000 - val_loss: 1179184768.0000 - val_mae: 24977.5469 - val_mse: 1179184768.0000
Epoch 74/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 1074259456.0000 - mae: 24049.3906 - mse: 1074259456.0000 - val_loss: 1178633216.0000 - val_mae: 25006.5430 - val_mse: 1178633216.0000
Epoch 75/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 1215211136.0000 - mae: 24859.9844 - mse: 1215211136.0000 - val_loss: 1172204416.0000 - val_mae: 25048.1426 - val_mse: 1172204416.0000
Epoch 76/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 1069192128.0000 - mae: 23882.8691 - mse: 1069192128.0000 - val_loss: 1172331904.0000 - val_mae: 24939.2031 - val_mse: 1172331904.0000
Epoch 77/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 1100836352.0000 - mae: 24393.5508 - mse: 1100836352.0000 - val_loss: 1160927232.0000 - val_mae: 24922.0137 - val_mse: 1160927232.0000
Epoch 78/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 1197070720.0000 - mae: 24915.0488 - mse: 1197070720.0000 - val_loss: 1147889280.0000 - val_mae: 24868.3613 - val_mse: 1147889280.0000
Epoch 79/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 1131603712.0000 - mae: 24638.0801 - mse: 1131603712.0000 - val_loss: 1141957376.0000 - val_mae: 24796.4746 - val_mse: 1141957376.0000
Epoch 80/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 1043138624.0000 - mae: 24077.6504 - mse: 1043138624.0000 - val_loss: 1133982592.0000 - val_mae: 24566.3340 - val_mse: 1133982592.0000
Epoch 81/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1118565120.0000 - mae: 24278.1602 - mse: 1118565120.0000 - val_loss: 1129844096.0000 - val_mae: 24389.1758 - val_mse: 1129844096.0000
Epoch 82/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1166625280.0000 - mae: 24380.0469 - mse: 1166625280.0000 - val_loss: 1119681920.0000 - val_mae: 24440.8398 - val_mse: 1119681920.0000
Epoch 83/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1067264064.0000 - mae: 24055.9355 - mse: 1067264064.0000 - val_loss: 1114775808.0000 - val_mae: 24301.9746 - val_mse: 1114775808.0000
Epoch 84/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1042199232.0000 - mae: 23778.1523 - mse: 1042199232.0000 - val_loss: 1106726528.0000 - val_mae: 24161.0488 - val_mse: 1106726528.0000
Epoch 85/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1044921408.0000 - mae: 23268.8535 - mse: 1044921408.0000 - val_loss: 1098592896.0000 - val_mae: 24133.6289 - val_mse: 1098592896.0000
Epoch 86/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1079401600.0000 - mae: 23781.4023 - mse: 1079401600.0000 - val_loss: 1098736128.0000 - val_mae: 24153.9590 - val_mse: 1098736128.0000
Epoch 87/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1122713600.0000 - mae: 24591.0703 - mse: 1122713600.0000 - val_loss: 1103111168.0000 - val_mae: 24259.2344 - val_mse: 1103111168.0000
Epoch 88/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 970468288.0000 - mae: 22888.8379 - mse: 970468288.0000 - val_loss: 1092936832.0000 - val_mae: 24134.1641 - val_mse: 1092936832.0000
Epoch 89/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 989956480.0000 - mae: 22765.7598 - mse: 989956480.0000 - val_loss: 1091872640.0000 - val_mae: 23981.6895 - val_mse: 1091872640.0000
Epoch 90/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1012339264.0000 - mae: 23256.5312 - mse: 1012339264.0000 - val_loss: 1093263104.0000 - val_mae: 23945.1543 - val_mse: 1093263104.0000
Epoch 91/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 942885184.0000 - mae: 23123.0195 - mse: 942885184.0000 - val_loss: 1093154432.0000 - val_mae: 23946.7344 - val_mse: 1093154432.0000
Epoch 92/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 986745280.0000 - mae: 23810.2266 - mse: 986745280.0000 - val_loss: 1092336512.0000 - val_mae: 23961.3145 - val_mse: 1092336512.0000
Epoch 93/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1051806784.0000 - mae: 23413.2441 - mse: 1051806784.0000 - val_loss: 1086200704.0000 - val_mae: 23800.7500 - val_mse: 1086200704.0000
Epoch 94/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1004131008.0000 - mae: 23101.3984 - mse: 1004131008.0000 - val_loss: 1065720832.0000 - val_mae: 23609.5039 - val_mse: 1065720832.0000
Epoch 95/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 949971072.0000 - mae: 22607.8125 - mse: 949971072.0000 - val_loss: 1069251392.0000 - val_mae: 23754.1406 - val_mse: 1069251392.0000
Epoch 96/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 915794496.0000 - mae: 22256.3652 - mse: 915794496.0000 - val_loss: 1055931136.0000 - val_mae: 23643.2363 - val_mse: 1055931136.0000
Epoch 97/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 972024704.0000 - mae: 22566.2988 - mse: 972024704.0000 - val_loss: 1053838208.0000 - val_mae: 23614.1621 - val_mse: 1053838208.0000
Epoch 98/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 936016896.0000 - mae: 22380.0801 - mse: 936016896.0000 - val_loss: 1049255296.0000 - val_mae: 23498.0371 - val_mse: 1049255296.0000
Epoch 99/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 926033920.0000 - mae: 22551.3477 - mse: 926033920.0000 - val_loss: 1046486848.0000 - val_mae: 23521.9453 - val_mse: 1046486848.0000
Epoch 100/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 943667264.0000 - mae: 22427.2695 - mse: 943667264.0000 - val_loss: 1054758784.0000 - val_mae: 23429.7520 - val_mse: 1054758784.0000

In [ ]:
# ### 모델 평가
# 훈련된 모델을 테스트 데이터로 평가하여 모델의 성능을 확인합니다.
loss, mae, mse = model.evaluate(X_test_scaled, y_test, verbose=0)
print(f"테스트 손실 (MSE): {loss:.4f}")
print(f"테스트 MAE: {mae:.4f}")
print(f"테스트 RMSE: {np.sqrt(mse):.4f}")

테스트 손실 (MSE): 1229369344.0000
테스트 MAE: 24297.6602
테스트 RMSE: 35062.3636

In [ ]:
correlation_matrix = df_encoded.corr(numeric_only=True)
correlations_with_saleprice = correlation_matrix['SalePrice'].abs().sort_values(ascending=False)

# 상관관계가 낮은 특성 확인 (예: 0.1 미만)
low_corr_features = correlations_with_saleprice[correlations_with_saleprice < 0.1].index.tolist()

print("Correlation with SalePrice (absolute value, sorted):")
print(correlations_with_saleprice.head(20))

print(f"\nFeatures with absolute correlation < 0.1 with SalePrice: {len(low_corr_features)} features")
print(low_corr_features[:10]) # 상위 10개만 출력

Correlation with SalePrice (absolute value, sorted):
SalePrice           1.000000
OverallQual         0.790982
GrLivArea           0.708624
GarageCars          0.640409
GarageArea          0.623431
TotalBsmtSF         0.613581
1stFlrSF            0.605852
ExterQual_TA        0.589044
FullBath            0.560664
BsmtQual_Ex         0.553105
TotRmsAbvGrd        0.533723
YearBuilt           0.522897
KitchenQual_TA      0.519298
YearRemodAdd        0.507101
KitchenQual_Ex      0.504094
Foundation_PConc    0.497734
MasVnrArea          0.475241
GarageYrBlt         0.470177
Fireplaces          0.466929
ExterQual_Gd        0.452466
Name: SalePrice, dtype: float64

Features with absolute correlation < 0.1 with SalePrice: 156 features
['Exterior2nd_AsbShng', 'BldgType_Twnhs', 'BldgType_2fmCon', 'Exterior1st_HdBoard', 'HouseStyle_SFoyer', 'Heating_GasA', 'PoolArea', 'Heating_Grav', 'MSZoning_FV', 'BsmtCond_Gd']

In [ ]:
X_filtered = X.drop(columns=low_corr_features, errors='ignore')

# 필터링된 X 데이터프레임의 상위 5개 행과 형태를 출력합니다.
display(X_filtered.head())
print(f"Original X shape: {X.shape}")
print(f"Filtered X shape: {X_filtered.shape}")

X = X_filtered # X를 필터링된 데이터프레임으로 업데이트

# 훈련 데이터와 테스트 데이터도 다시 분할 및 스케일링
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

print(f"\n훈련 세트 크기 (필터링 후): {X_train_scaled.shape}")
print(f"테스트 세트 크기 (필터링 후): {X_test_scaled.shape}")

,LotFrontage,LotArea,OverallQual,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,BsmtUnfSF,TotalBsmtSF,1stFlrSF,...,PavedDrive_N,PavedDrive_Y,PoolQC_Ex,Fence_GdWo,Fence_MnPrv,SaleType_New,SaleType_WD,SaleCondition_Abnorml,SaleCondition_Normal,SaleCondition_Partial
0,65.0,8450,7,2003,2003,196.0,706,150,856,856,...,False,True,False,False,False,False,True,False,True,False
1,80.0,9600,6,1976,1976,0.0,978,284,1262,1262,...,False,True,False,False,False,False,True,False,True,False
2,68.0,11250,7,2001,2002,162.0,486,434,920,920,...,False,True,False,False,False,False,True,False,True,False
3,60.0,9550,7,1915,1970,0.0,216,540,756,961,...,False,True,False,False,False,False,True,True,False,False
4,84.0,14260,8,2000,2000,350.0,655,490,1145,1145,...,False,True,False,False,False,False,True,False,True,False

Original X shape: (1460, 288)
Filtered X shape: (1460, 132)

훈련 세트 크기 (필터링 후): (1168, 132)
테스트 세트 크기 (필터링 후): (292, 132)